services:
  backend:
      image: chadchoud/atelier-backend:v3
      build:
        context: ./backend
      ports:
        - "8787:8787"
      networks:
        - my-network

  frontend:
      image: chadchoud/atelier-frontend:v3
      build:
        context: ./frontend
      ports:
        - "80:80"
      depends_on:
        - backend
      networks:
        - my-network

networks:
  my-network:
    driver: bridge